jobs:
  node/test:
    docker:
    - image: cimg/node:stable
    steps:
    - checkout
    - app-dir: ~/project
version: 2.1
orbs:
  node: circleci/node@3.0.0
workflows:
  node-tests:
    jobs:
      - node/test